# Generated by Django 3.2.6 on 2021-09-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='img',
        ),
    ]
